name: Frigate Proxy
version: 1.8.22
panel_icon: "mdi:cctv"
panel_title: Frigate
slug: frigate-proxy
description: Proxy addon for multiple Frigate instances
url: "https://github.com/blakeblackshear/frigate"
startup: application
boot: auto
init: false
webui: "http://[HOST]:[PORT:5000]/"
watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
options:
  instances:
    - name: "Main Frigate"
      description: "Primary Frigate instance"
      server: "http://frigate.local:5000"
      path: "/main"
      proxy_pass_host: true
      proxy_pass_real_ip: true
schema:
  instances:
    - name: str
      description: str
      server: str
      path: str
      proxy_pass_host: bool
      proxy_pass_real_ip: bool
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
